"""empty message

Revision ID: 216c676b5705
Revises: 
Create Date: 2020-04-20 13:52:35.751658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216c676b5705'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweet', sa.String(length=128), nullable=True),
    sa.Column('user', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twitter')
    # ### end Alembic commands ###
